### ISSUE TITLE
BufferOverflowException when running ensureRecentMetacello

### ISSUE THREAD

**Issue by arundilipan** [hpi-swa/trufflesqueak#110] opened 2020-04-12 19:22 UTC
**Reproduction**

When running `graalsqueak GraalSqueak-1.0.0-rc8.image`, World>do>`Installer ensureRecentMetacello`.

**Error**

```
ERROR: java.nio.BufferOverflowException
org.graalvm.polyglot.PolyglotException: java.nio.BufferOverflowException
```

**Comment by fniephaus** [comment] 2020-05-29 06:04
This looks like a duplicate of #92.

**Closed** 2020-06-24 09:55 UTC
Labels: bug, help wanted, linux
